"""adding public_id column in story model

Revision ID: 0c3bf66c3f37
Revises: 624cd29f87e2
Create Date: 2026-05-07 19:48:06.531281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3bf66c3f37'
down_revision: Union[str, Sequence[str], None] = '624cd29f87e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('public_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'public_id')
    # ### end Alembic commands ###
