"""add public_id column in user model

Revision ID: 35c6cf29ea4e
Revises: 98c9e7da3310
Create Date: 2026-04-29 17:04:15.529262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c6cf29ea4e'
down_revision: Union[str, Sequence[str], None] = '98c9e7da3310'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_id')
    # ### end Alembic commands ###
