"""deleting expire_at colummn from 
story model

Revision ID: 624cd29f87e2
Revises: 5be72b54e467
Create Date: 2026-05-06 19:05:09.756707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '624cd29f87e2'
down_revision: Union[str, Sequence[str], None] = '5be72b54e467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_expires_at'), table_name='stories')
    op.drop_column('stories', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_stories_expires_at'), 'stories', ['expires_at'], unique=False)
    # ### end Alembic commands ###
