"""add public_id column in post model

Revision ID: 9948e2f7a5c9
Revises: c1c79225d798
Create Date: 2026-04-24 19:15:06.517319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9948e2f7a5c9'
down_revision: Union[str, Sequence[str], None] = 'c1c79225d798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_images', sa.Column('public_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_images', 'public_id')
    # ### end Alembic commands ###
